title: Xiao Hu
subtitle: Purdue M.S. ECE Student
description: >- # this means to ignore newlines until "baseurl:"
  an ECE MS student at Purdue University.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    # - text: About Me
    #   url: /about
    # - text: Blog
    #   url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Resume
      url: /resume
    - text: Contact Me
      url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit these details

author_logo: profile.jpeg
author: Xiao Hu
author_bio: Hi, my name is Xiao Hu. I am a M.S. student in Electircal and Computer Engineering major at Purdue University. My research broadly connects to the fields of human-computer interaction, low-power computer vision, fairness in artificial intelligence, machine learning, and full-stack web development. I also have experiences in building fair training visual dataset for detecting Personal Protective Equipment (PPE) in factory environment.
author_email: "hu440@purdue.edu"
author_location: West Lafayette, IN, USA
author_website_url: "https://xiaohu.info"
typewrite-text: activly looking for an internship opportunity for 2021 Summer

author_education_details:
              - college_logo: purdue_logo.jpg
                college_name: Purdue University (2020 - 2022)
                college_url: https://engineering.purdue.edu/ECE
                college_degree: Elertical and Computer Engineering
                description: Master of Engineering
                visibility: true
              - college_logo: purdue_logo.jpg
                college_name: Purdue University (2016 - 2020)
                college_url: https://www.cs.purdue.edu/
                college_degree: Computer Science
                description: Bachelor of Science
                visibility: true

author_publications:
            - title: Crowdsourcing Detection of Sampling Biases in Image Datasets
              thumbnail: pub_crowdsourcing01.png
              authors: Xiao Hu, Haobo Wang, Anirudh Vegesana, Somesh Dube, Kaiwen Yu, Gore Kao, Shuo-Han Chen, Yung-Hsiang Lu, George K. Thiruvathukal, Ming Yin
              publisher: The International World Wide Web Conference (WWW), April, 2020
              url: https://dl.acm.org/doi/fullHtml/10.1145/3366423.3380063
              visibility: true

            - title: Discovering Biases in Image Datasets with the Crowd
              thumbnail: pub_crowdsourcing02.png
              authors: Xiao Hu, Haobo Wang, Anirudh Vegesana, Somesh Dube, Kaiwen Yu, Gore Kao, Shuo-Han Chen, Yung-Hsiang Lu, George K. Thiruvathukal, Ming Yin
              publisher: The seventh AAAI Conference on Human Computation and Crowdsourcing (HCOMP), October, 2019
              url: http://mingyin.org/paper/HCOMP-19/BiasDetection_camera.pdf
              visibility: true

            - title: A Large-scale Annotated Mechanical Components Benchmark for Classification and Retrieval Tasks with Deep Neural Networks
              thumbnail: pub_mebp.png
              authors: Sangpil Kim, Hyung-gun Chi, Xiao Hu, Qixing Huang, Karthik Ramani
              publisher: In proceedings of 16th European Conference on Computer Vision (ECCV), August, 2020
              url: https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123630171.pdf
              visibility: true

            - title: First-Person View Hand Segmentation ofMulti-Modal Hand Activity Video Dataset
              thumbnail: pub_bmvc.png
              authors: Sangpil Kim, Hyung-gun Chi, Xiao Hu, Anirudh Vegesana, Karthik Ramani
              publisher: The British Machine Vision Conference (BMVC), September, 2020
              url:
              visibility: true

            - title: Observing Responses to the COVID-19 Pandemic using Worldwide Network Cameras
              thumbnail: pub_covid.png
              authors:  Isha Ghodgaonkar, Abhinav Goel, Fischer Bordwell, Caleb Tung, Sara Aghajanzadeh, Noah Curran, Ryan Chen, Kaiwen Yu, Sneha Mahapatra, Vishnu Banna, Gore Kao, Kate Lee, Xiao Hu, Nick Eliopolous, Akhil Chinnakotla, Damini Rijhwani, Ashley Kim, Aditya Chakraborty, Mark Daniel Ward, Yung-Hsiang Lu, George K. Thiruvathukal
              publisher: 2020 Computer and Society
              url: https://arxiv.org/pdf/2005.09091.pdf
              visibility: true

            - title: Low-Power Computer Vision Status, Challenges, and Opportunities
              thumbnail: pub_lpcv.png
              authors: Sergei Alyamkin, Matthew Ardi, Alexander C Berg, Achille Brighton, Bo Chen, Yiran Chen, Hsin-Pai Cheng, Zichen Fan, Chen Feng, Bo Fu, Kent Gauen, Abhinav Goel, Alexander Goncharenko, Xuyang Guo, Soonhoi Ha, Andrew Howard, Xiao Hu, Yuanjun Huang, Donghyun Kang, Jaeyoun Kim, Jong Gook Ko, Alexander Kondratyev, Junhyeok Lee, Seungjae Lee, Suwoong Lee, Zichao Li, Zhiyu Liang, Juzheng Liu, Xin Liu, Yang Lu, Yung-Hsiang Lu, Deeptanshu Malik, Hong Hanh Nguyen, Eunbyung Park, Denis Repin, Liang Shen, Tao Sheng, Fei Sun, David Svitov, George K Thiruvathukal, Baiwu Zhang, Jingchi Zhang, Xiaopeng Zhang, Shaojie Zhuo
              publisher: 2019 IEEE Journal on Emerging and Selected Topics in Circuits and Systems
              url: https://arxiv.org/pdf/1904.07714.pdf
              visibility: true


author_work_experiences:
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true


author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
# twitter_username: johndoe
github_username:  SionHu
facebook_username: xiao.hu.sion
linkedin_username: xiao-hu-purdue
instagram_username: sion_hu
wechat_username: hx9865
# behance_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: SionHu

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: hu440@purdue.edu

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_education_details: true
show_author_publications: true
show_author_work_experiences: false
show_author_project_details: false

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
